### PR TITLE
Software Specification and Connextra

### PR DESCRIPTION
**Pull request by cangelides**
@rchu15 check out my section on software specification and Connextra and let me know what you think.  I'm having some trouble formatting the example user stories so that they are grouped together correctly.  Do you know what i should do to fix those?  I'm still learning the markdown. :neckbeard:

### CODE REVIEW

**Comment by rchu15** [comment]
@cangelides this looks great! i especially love how you've used the user stories framework to help think through a very practical and real business problem!

regarding the formatting, check out the examples section of this:
https://guides.github.com/features/mastering-markdown/#syntax
you could look at a list or play with the headers

also, the section on 'nested lists' is helpful too to help visualize it better:
https://help.github.com/articles/markdown-basics/

and p.s. i love that monster emoji that you found!! :laughing:

**Comment by rchu15** [comment]
@cangelides may want to check your last paragraph, just a quick typo: tp rather than to in the sentence "The process helped us tp develop a much more comprehensive "

**Comment by cangelides** [comment]
Thanks @rchu15. I added in an image and link too, formatted the user stories (thx for guidance), and fixed the typo in last graph.  I think this is good to go.  What do you think?

**Comment by rchu15** [comment]
i LOVE your dilbert cartoon @cangelides !! 

the formatting for the epics and user stories look great - nice job!

looks good to go! :+1:

**Comment by cangelides** [comment]
@chowdhury because you are a cool EMBA like us, can we get your opinion?

**Comment by chowdhury** [comment]
@cangelides love it! let's ship it! :+1:

**Comment by cangelides** [comment]
@rchu15 pulled in my page on software specification to the master branch of our repo.  I'll move to ship the lessons learned to the main repo

**Comment by rchu15** [comment]
@cangelides sounds great! :+1:

**Pull request merged**
