### PR TITLE
Using kanban boards to manage projects

### PR DESCRIPTION
**Pull request by rchu15**
@cangelides do you mind sending your thoughts over? thank you! :smile:

### CODE REVIEW

**Comment by cangelides** [comment]
This looks awesome Robin.  I agree that the Kanban method for managing software development was one of the most helpful takeaways from that section of the course.  I especially loved how you have already put it into practice at work and I think that your first cut at the board is great.  I'm sure some practice with it will refine the structure even further.  I talked about using a Kanban board with my team as well to manage some of the statistical analysis we do so let's keep each other posted on how it works out--the benefits, challenges, etc.  

Also, for your viewing pleasure I thought you would enjoy this clip from Silicon Valley on Scrum and Kanban.  https://www.youtube.com/watch?v=HsJoLvRbri0/.  I  feel like we can finally appreciate it now.

**Comment by rchu15** [comment]
@cangelides this youtube clip :movie_camera: is amazing.. i :heart: it! :clap: 

the board at work will likely need some tweaking - the concept was well-received, but i think we do need to think through the color coding a bit. keep me posted with yours!

**Comment by cangelides** [comment]
@rchu15 Are we set to merge your document into our master version of the repo?  Or are you still making changes?

**Comment by rchu15** [comment]
@cangelides just wanted to make a quick addition and add in an image.. will update in a few

**Comment by rchu15** [comment]
@cangelides just added the image (needed 1 image and 1 link). we are good to go :+1: 

@chowdhury, since you have a brilliant mind, does this look okay? thanks!

**Comment by cangelides** [comment]
@rchu15 looks great!  :+1: I think this is good to go and I'll merge into master as soon as we hear from @chowdhury.

**Comment by chowdhury** [comment]
@rchu15 awesome, and thanks for the praise. good to go! :+1:

**Comment by cangelides** [comment]
@rchu15 I've merged your branch into the master

**Pull request merged**
